version: '3.5'
services:
  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    networks:
      - back
    volumes: 
        - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
    ports:
      - 8081:8081
    networks:
      - front
      - back
    depends_on:
      - mongo

  proxy:
    image: nginx
    container_name: nginx-rvp
    ports: 
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    restart: always
    networks:
      - front


networks:
  front:
  back:

volumes:
  mongo-data:
